name: NB Next customisations
on: 
  push:
    branches: [develop]
env:
  DEFAULT_BRANCH: "develop"
  UPDATED_BRANCH: "develop-updated"
  PATCH_DIR: ${{github.event.repository.name}}/customisation/patches/${{github.event.repository.name}}


jobs:
  nbnext:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ env.DEFAULT_BRANCH }}
      - run: git checkout -b ${{ env.UPDATED_BRANCH }}


      - name: Checkout customisations
        uses: actions/checkout@v3
        with:
          repository: thenbdev/Customisations
          path: customisation

      - name: Apply patches
        # if: hashFiles('$PATCH_DIR')!=''  #TODO: why is this not working
        continue-on-error: true
        # Remove the exit 1 and then remove continue-on-errors in here
        run: |
          shopt -s nullglob

          cd ..
          if [ -d "$PATCH_DIR" ]; then
            echo "Patches found in $PATCH_DIR:"
            echo "$PATCH_DIR"/*.patch
            for patch in "$PATCH_DIR"/*.patch; do
              if [ -f "$patch" ]; then
                echo "Starting $patch"
                if git apply --directory=${{github.event.repository.name}} --ignore-space-change --verbose --check "$patch"; then
                  echo "Applying patch $(basename "${patch%.*}")"
                  git apply --directory=${{github.event.repository.name}} --ignore-space-change --verbose "$patch" || exit 1
                  echo "Patch $(basename "${patch%.*}") applied"
                else
                  echo "Partially applied, or not applied at all"
                  if git apply --directory=${{github.event.repository.name}} --ignore-space-change --verbose --reverse --check "$patch"; then
                      git apply --directory=${{github.event.repository.name}} --ignore-space-change --reject --whitespace=fix "$patch" || exit 1
                      echo "Applied patch ${patch##*/}"
                  else
                    echo "Failed to apply patch $(basename "${patch%.*}"). Check if there is a confict."
                    # exit 1
                  fi
                fi
              fi
            done
          else
            echo "Patch directory $PATCH_DIR not found."
          fi

      - name: Cleanup
        run: rm -rf customisation

      - name: Commit and Push - Patches
        uses: thenbdev/cleanup-and-push@main
        with:
          branch: ${{ env.UPDATED_BRANCH }}
          commit_message: "Automatically applied patches"

      - name: Find and Replace links (direct/docs, youtube)
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: (erpnext.com|www.youtube.com)
          replace: "nbnextlinks"
          regex: true

      - name: Find and Replace erpnext(without spaces)
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          # Replace all code ERPNext to NBNext, so space doesn't cause build errors
          # Todo: /i doesn't work, make it case insensitive
          find: "(erpnext|ERPNext|ERPnext|erpNext)"  
          replace: "NBNext"
          regex: true

      - name: Find and Replace erp next (with space)
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          # Todo: /i doesn't work, make it case insensitive
          find: "(erp next|ERP next|ERP Next|erp Next)"
          replace: "NB Next"
          regex: true

      - name: Find and Replace frappe
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          # Replace all code ERPNext to NBNext, so space doesn't cause build errors
          # Todo: /i doesn't work, make it case insensitive
          find: "(frappe|Frappe)"  
          replace: "theNBdev"
          regex: true

      # Build fixes
      # TODO: Check this in translations
      - name: Module build fixes
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          exclude: "**/translations/*"
          find: "NB Next Integrations"
          replace: "ERPNext Integrations"
          regex: false

      # TODO: change the download/logo location to customsation repo
      - name: Find and Replace logo
        if: ${{ hashFiles('**/erpnext-logo.*') }}
        # TODO: figure out where is the file and replace it. currently static handling
        run: |
          cd erpnext/public/images
          wget -N http://thenb.nbnext.in/assets/erpnext/images/erpnext-logo.svg
          wget -N http://thenb.nbnext.in/assets/erpnext/images/erpnext-logo.png
          wget -N http://thenb.nbnext.in/assets/erpnext/images/erpnext-favicon.svg

      - name: Commit and Push - Replacements
        uses: thenbdev/cleanup-and-push@main
        with:
          branch: ${{ env.UPDATED_BRANCH }}
          commit_message: "NB Next Replacements Automated commit"


      # Rename files and folders
      - name: Rename erpnext to nbnext
        run: |
          if [ -e *erpnext* ]; then
            mv *erpnext* $(echo *erpnext* | sed 's/erpnext/nbnext/')
          fi

      - name: Rename erp_next to nb_next
        run: |
          if [ -e *erp_next* ]; then
            mv *erp_next* $(echo *erp_next* | sed 's/erp_next/nb_next/')
          fi

      - name: Rename Frappe to Thenb
        run: |
          if [ -e *frappe* ]; then
            mv *frappe* $(echo *frappe* | sed 's/frappe/thenb/')
          fi

      - name: Commit and Push - rename files and folders
        uses: thenbdev/cleanup-and-push@main
        with:
          branch: ${{ env.UPDATED_BRANCH }}
          commit_message: "NB Next Replacements Rename files and folders"
